name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  ci:
    uses: vanillaes/.github/.github/workflows/verify.yml@main

  cd-npm:
    needs: ci
    uses: vanillaes/.github/.github/workflows/npm.yml@main
    secrets: inherit

  cd-gh:
    needs: ci
    uses: vanillaes/.github/.github/workflows/gh.yml@main
    secrets: inherit

  cd-jsr:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - id: check_jsr
        run: |
          if [ -f "jsr.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v6
      - if: steps.check_jsr.outputs.exists == 'true'
        run: npx jsr publish
